version: "3"

name: tourquest
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
  server:
    build:
      context: ./.nginx
      dockerfile: Dockerfile
      args:
        - HTTP_ADDRESS=backend:8000
        - WS_ADDRESS=backend:8001
    restart: always
    depends_on:
      - backend
      