version: "3"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    ports:
      - 8000:8000
      - 8001:8001
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres?schema=public
  server:
    build:
      context: ./.nginx
      dockerfile: Dockerfile
      args:
        - HTTP_ADDRESS=http://backend:8000
        - WS_ADDRESS=http://backend:8001
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  postgres-data:
