version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL="${DATABASE_URL}"
  server:
    build:
      context: ./.nginx
      dockerfile: Dockerfile
      args:
        - HTTP_ADDRESS=http://backend:8000
        - WS_ADDRESS=http://backend:8001
    restart: always
      - 8090:80
    depends_on:
      - backend
      